IO1-3038: changed font size of references match the other text
bloxapp/ssv-web pull request #139
Opened 2023-04-10 06:40 UTC by axelrod-blox

2023-04-16 09:34 UTC, meshin-blox requested changes

2023-04-16 09:34 UTC, meshin-blox commented on src/app/components/applications/SSV/MyAccount/common/LiquidationStateError/LiquidationStateError.tsx
> +            return <div>Withdrawing the requested amount will liquidate your cluster, which will result in inactivation (<LinkText className={classes.LinkText} text={'penalties on the beacon chain'}
Move the link to config constants

2023-04-16 09:34 UTC, meshin-blox commented on src/app/components/applications/SSV/MyAccount/common/LiquidationStateError/LiquidationStateError.tsx
> +            <LinkText className={classes.LinkText} text={'Read more on liquidations'} link={'https://docs.ssv.network/learn/protocol-overview/tokenomics/liquidations'} />
Link to config

2023-04-17 06:41 UTC, axelrod-blox commented on src/app/components/applications/SSV/MyAccount/common/LiquidationStateError/LiquidationStateError.tsx
> +            return <div>Withdrawing the requested amount will liquidate your cluster, which will result in inactivation (<LinkText className={classes.LinkText} text={'penalties on the beacon chain'}
done

2023-04-17 06:41 UTC, axelrod-blox commented on src/app/components/applications/SSV/MyAccount/common/LiquidationStateError/LiquidationStateError.tsx
> +            <LinkText className={classes.LinkText} text={'Read more on liquidations'} link={'https://docs.ssv.network/learn/protocol-overview/tokenomics/liquidations'} />
done

2023-04-19 10:15 UTC, meshin-blox approved these changes

2023-04-19 10:15 UTC, merged