merge stage to main
bloxapp/ssv-web pull request #265
Opened 2023-06-18 10:39 UTC by axelrod-blox

2023-06-18 10:53 UTC, andrew-blox approved these changes

2023-06-18 15:18 UTC, meshin-dev approved these changes

2023-06-18 15:18 UTC, meshin-dev commented
This should not be merged until we change secrets to the new contract which should be deployed today

2023-06-18 17:03 UTC, meshin-dev requested changes

2023-06-18 17:03 UTC, meshin-dev commented on .env.development
> +  REACT_APP_FAUCET_PAGE=true
Comment it back again

2023-06-19 08:31 UTC, meshin-dev approved these changes

2023-06-19 15:07 UTC, merged