IO1-3650: hided empty and liquidated cluster
bloxapp/ssv-web pull request #279
Opened 2023-06-26 09:09 UTC by axelrod-blox

![Screenshot 2023-06-26 at 12 08 05](https://github.com/bloxapp/ssv-web/assets/128966996/15f1af1e-91c3-432b-969f-5f5c88beedc3)
![Screenshot 2023-06-26 at 12 09 24](https://github.com/bloxapp/ssv-web/assets/128966996/45e889fd-0c3f-4792-b649-f9aedfc2a81d)

2023-06-26 11:17 UTC, meshin-dev requested changes
Cluster can be not liquidated and without validators. Or cluster can have validators and be liquidated. In Jira task condition should be AND, not OR like implementing here. 

Please make sure that final result is satisfying different states of that cluster and validator count

2023-06-26 11:57 UTC, axelrod-blox commented
> Cluster can be not liquidated and without validators. Or cluster can have validators and be liquidated. In Jira task condition should be AND, not OR like implementing here.
> 
> Please make sure that final result is satisfying different states of that cluster and validator count
![Screenshot 2023-06-26 at 14 57 22](https://github.com/bloxapp/ssv-web/assets/128966996/a9f4acc3-9817-48cf-a074-4d7be88a2a0e)
![Screenshot 2023-06-26 at 14 57 16](https://github.com/bloxapp/ssv-web/assets/128966996/c9a88892-6968-4a80-bbc9-e0db80ba611e)

2023-06-26 12:04 UTC, meshin-dev approved these changes

2023-06-27 10:37 UTC, andrew-blox approved these changes

2023-06-27 12:03 UTC, merged