IO1-3581: added validation if pk of operator exist
bloxapp/ssv-web pull request #282
Opened 2023-06-29 07:43 UTC by axelrod-blox

![Screenshot 2023-06-29 at 8 50 48](https://github.com/bloxapp/ssv-web/assets/128966996/8bffcaaf-5f04-41bd-b765-a2b4bdec4a25)

2023-06-29 09:11 UTC, andrew-blox approved these changes

2023-07-04 14:54 UTC, meshin-dev requested changes

2023-07-04 14:54 UTC, meshin-dev commented on src/lib/utils/validatesInputs.tsx
> +       return false;
Indentation is wrong in this function

2023-07-09 06:27 UTC, axelrod-blox commented on src/lib/utils/validatesInputs.tsx
> +       return false;
done

2023-07-09 09:19 UTC, meshin-dev approved these changes

2023-07-09 09:19 UTC, meshin-dev commented on src/lib/utils/validatesInputs.tsx
> +       return false;
Sorry there is one more comment. You can simplify this return to be one instead of 2

2023-07-10 11:59 UTC, meshin-dev approved these changes

2023-07-13 09:43 UTC, merged