IO1-3777: fixed validation bug
bloxapp/ssv-web pull request #291
Opened 2023-07-11 13:25 UTC by axelrod-blox

![Screenshot 2023-07-11 at 16 24 44](https://github.com/bloxapp/ssv-web/assets/128966996/d5245b47-0b47-4a8c-a6ce-8f066c1374c4)

2023-07-11 13:38 UTC, meshin-dev requested changes

2023-07-11 13:38 UTC, meshin-dev commented on src/app/common/stores/applications/SsvWeb/OperatorMetadata.store.ts
> +                metadataContainsError = fieldEntity.errorMessage ? true : metadataContainsError;
`!!fieldEntity.errorMessage || metadataContainsError`

2023-07-11 18:14 UTC, axelrod-blox commented on src/app/common/stores/applications/SsvWeb/OperatorMetadata.store.ts
> +                metadataContainsError = fieldEntity.errorMessage ? true : metadataContainsError;
done

2023-07-13 09:25 UTC, meshin-dev approved these changes

2023-07-13 09:35 UTC, merged