added new button, moved link into tooltip
bloxapp/ssv-web pull request #444
Opened 2023-12-12 09:34 UTC by axelrod-blox

<img width="864" alt="Screenshot 2023-12-12 at 15 33 50" src="https://github.com/bloxapp/ssv-web/assets/128966996/9c3b45ab-ac5d-4848-a840-8694624296dc">

2023-12-12 10:01 UTC, IlyaVi approved these changes

2023-12-12 10:01 UTC, IlyaVi commented on src/app/components/applications/SSV/RegisterValidatorHome/components/SelectOperators/components/FirstSquare/components/ClusterSize/ClusterSize.tsx
> +            {sizes.map((size: number, index: number) => <Grid key={index} onClick={() => clusterSizeHandler(size)} className={`${classes.ClusterSizeButton} ${size === currentClusterSize && classes.Ch
this will cause warning during compilation
use key={`${index}${size}`}

2023-12-12 10:01 UTC, IlyaVi commented on src/app/components/applications/SSV/RegisterValidatorHome/RegisterValidatorHome.tsx
> +            <PrimaryButton text={'Generate new key shares'} submitFunction={moveToSelectOperators} withoutLoader/>
texts to transalations

2023-12-12 10:01 UTC, IlyaVi commented on src/app/components/applications/SSV/RegisterValidatorHome/RegisterValidatorHome.tsx
> +    validatorStore.clearKeyStoreFlowData();
this hook will run every render cycle - is it meant to be like this?

2023-12-12 10:01 UTC, IlyaVi commented on src/app/components/applications/SSV/RegisterValidatorHome/RegisterValidatorHome.tsx
> +      text: 'An active Ethereum validator (deposited to Beacon Chain)',
texts to translations

2023-12-13 07:37 UTC, alexstolr requested changes
Please re-request review after you address Ilyas comments.

2023-12-13 07:37 UTC, alexstolr approved these changes
Please address Ilyas comments

2023-12-31 13:31 UTC, merged