included Israel into country restrictions and added error when for un…
bloxapp/ssv-web pull request #531
Opened 2024-02-01 14:59 UTC by axelrod-blox

…supported versions

2024-02-02 18:04 UTC, alexstolr requested changes
I still didn't finish the review but you can start handling my first comment while I review the rest.

2024-02-02 18:04 UTC, alexstolr commented on src/app/common/stores/applications/SsvWeb/Operator.store.ts
> +      console.log(e);
I see it mostly effects the next route redirect via setting applicationStore.strategyRedirect, and defines the pagination behavior when setting the url. You can catch at the caller of this (updateOperatorValidatorsLimit) function and said this values based on what we wnat (as well as console log). Move it there pls

2024-02-02 18:05 UTC, alexstolr commented on src/app/common/stores/applications/SsvWeb/Operator.store.ts
> +      console.log(e);
btw, which route we should take in scenario is a product decision, so best consult with Ariel.

2024-02-05 09:51 UTC, axelrod-blox commented on src/app/common/stores/applications/SsvWeb/Operator.store.ts
> +      console.log(e);
the catch case can happening if we provide incorrect contract address, changed this part with new message, 
I think we should speak with Ariel to create error page and show him in cases like this

2024-02-05 10:03 UTC, alexstolr commented on src/app/common/stores/applications/SsvWeb/Operator.store.ts
> +      console.log(e);
Actually I don't remember how I reached my above conclusion.

2024-02-05 10:30 UTC, alexstolr approved these changes

2024-02-05 12:18 UTC, merged