All networks support for rpc url (for WalletConnect only)
bloxapp/ssv-web pull request #583
Opened 2024-02-20 18:41 UTC by IlyaVi

2024-02-20 19:18 UTC, alexstolr commented on src/lib/utils/onboardHelper.ts
>        token: 'ETH',
```suggestion
      token: TOKEN_NAMES[NETWORKS.HOLESKY],
```

2024-02-20 19:24 UTC, alexstolr commented on src/services/contracts.service.ts
> +      let ethProvider;
Please add the type of new ethers.providers.JsonRpcProvider().

2024-02-20 19:29 UTC, alexstolr commented on src/services/contracts.service.ts
> +        if (network.networkId === HOLESKY_NETWORK_ID) {
ditto

2024-02-20 19:30 UTC, alexstolr requested changes
some small comments

2024-02-21 09:43 UTC, axelrod-blox approved these changes

2024-02-21 10:03 UTC, merged